apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: database
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: database
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: dbpass123
        - name: POSTGRES_USER
          value: inspirehep
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: APP_SERVER_NAME
          value: cveedback.co:31111
        image: postgres
        name: database
        resources: {}
      restartPolicy: Always
status: {}
