apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: database
  name: database
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    service: database
status:
  loadBalancer: {}
