apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: indexer
  name: indexer
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  selector:
    service: indexer
status:
  loadBalancer: {}
