apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: rabbitmq
status:
  loadBalancer: {}
