apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: rabbitmq
    spec:
      containers:
      - env:
        - name: APP_SERVER_NAME
          value: cveedback.co:5000
        image: rabbitmq
        name: rabbitmq
        resources: {}
      restartPolicy: Always
status: {}
