apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: redis
    spec:
      containers:
      - env:
        - name: APP_SERVER_NAME
          value: web:31111
        image: redis
        name: redis
        ports:
        - containerPort: 31111
        resources: {}
      restartPolicy: Always
status: {}
