apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  type: NodePort
  ports:
  - name: "81"
    port: 31111
    targetPort: 31111
    nodePort: 31111
  selector:
    service: web
status:
  loadBalancer: {}
