apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  type: NodePort
  ports:
  - name: "80"
    nodePort: 80
    port: 80
    targetPort: 80
  selector:
    service: web
status:
  loadBalancer: {}
