apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: zflower
  name: zflower
spec:
  ports:
  - name: "5555"
    port: 5555
    targetPort: 5555
  selector:
    service: zflower
status:
  loadBalancer: {}
